export const ACTION_TOOTLE_FILTERS = "layout.TOOTLE_FILTERS";
export const ACTION_TOOTLE_CATALOG = "layout.TOOTLE_CATALOG";
export const ACTION_TOOTLE_SHOPPING_CART = "layout.ACTION_TOOTLE_SHOPPING_CART";
